### ISSUE TITLE
Safari and Firefox Compatability

### ISSUE THREAD

**Issue by thomasjfox1** [NathanMarq/polymer-scaffold#3]
The site is not working in Safari. The custom elements are not displaying or being read at all by the browser. Might be something to do with the way webcomponents.js is loaded. I'm looking into more details soon.

The same also goes for FireFox. I have not tested any further though.

**Comment by NathanMarq** [comment]
Hey, sorry for the late response.

Wow, I can't believe I didn't even notice that... Looking into it now.

**Comment by thomasjfox1** [comment]
@NathanMarq No worries! Any luck?

**Comment by NathanMarq** [comment]
@thomasjfox1 I haven't fixed it completely yet, but the problem (at least with Firefox) looks like it's because Firefox forces HTML imports to be loaded last, regardless of where they are in the head of the html file. 

Since this means that polymer.html loads as one of the last files, the app.js file has no reference for what Polymer is, and so can't contribute to building the DOM. 

That's just my guess, because Firefox doesn't actually throw any errors, with the imports or even any JS errors, it just renders the base <polymer-app> element and calls it quits.

Needless to say, I'm still working on it :) Have you looked into it at all?

**Comment by thomasjfox1** [comment]
@NathanMarq So on the Polymer get the code page it says with 1.0 we need to use webcomponents-lite.js. When I change that in the external scripts file it throws another error, but that may be a start. https://www.polymer-project.org/1.0/docs/start/getting-the-code.html
